Documentation:
  Enabled: false
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Rails:
  Enabled: true
AllCops:
  Include:
  Exclude:
    - '**/Rakefile'
    - '**/config.ru'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'