language: ruby
rvm:
  - 2.3.1
before_script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
script:
  - bundle exec rubocop
  - bundle exec rspec spec
notifications:
  email:
    recipients:
      - m2c.andre@gmail.com
      - patrickwreis@gmail.com
      - marciocavarzeri@gmail.com
      - lucenaaguiar@gmail.com
      - lguilherme.santos@live.com
    on_success: always
    on_failure: always
